DROP TABLE IF EXISTS visits CASCADE;
CREATE TABLE visits (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  venue_id INTEGER REFERENCES venues(id) ON DELETE CASCADE,
  created_at TIMESTAMP
);