DROP TABLE IF EXISTS stories CASCADE;
CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  review_id INTEGER REFERENCES reviews(id) ON DELETE CASCADE,
  video VARCHAR(255),
  image VARCHAR(255)
);